export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const CLEAN_ALBUMS_DATA = "CLEAN_ALBUMS_DATA";
export const CLEAN_AUTHORS_DATA = "CLEAN_AUTHORS_DATA";
export const CLEAN_TRACKS_DATA = "CLEAN_TRACKS_DATA";

export const SET_PARENT_DATA = "SET_PARENT_DATA";
export const SET_AUTHORS_DATA = "SET_AUTHORS_DATA";
export const SET_ALBUMS_DATA = "SET_ALBUMS_DATA";
export const SET_TRACKS_DATA = "SET_TRACKS_DATA";

export const CHANGE_CURRENT_TRACK = "CHANGE_CURRENT_TRACK";
export const CHANGE_CURRENT_ALBUM = "CHANGE_CURRENT_ALBUM";

export const FETCH_U_REQUEST = "FETCH_U_REQUEST";
export const FETCH_U_SUCCESS = "FETCH_U_SUCCESS";

export const FETCH_REGISTRATION_ERROR = "FETCH_REGISTRATION_ERROR";
export const FETCH_AUTHORIZATION_ERROR = "FETCH_AUTHORIZATION_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_TRACK_LIST = "SET_TRACK_LIST";
export const FETCH_T_ERROR = "FETCH_T_ERROR";
